<a href="https://colab.research.google.com/github/Fareeha10/Class2_Quater2_PIAIC/blob/master/BooleanIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [5]:
arrid = np.array([213,54,67,22])
arrid


array([213,  54,  67,  22])

In [7]:
arrid[1:3]

array([54, 67])

In [8]:
arrid[-1]

22

In [10]:
arr2d=([[112,54,67,89,34,55],[44,22,111,77,88,90]])
arr2d


[[112, 54, 67, 89, 34, 55], [44, 22, 111, 77, 88, 90]]

In [0]:
#right side is for  col
#left for row
#2d[r,c]
'''2d[st:en,st:en] for slicing'''
arr3d.ndim   #demension

In [0]:
arr3d.shape

In [0]:
arr3d = np.array([[[12,13,14,15],[21,32,43,54],[1,5,3,2]]])

In [16]:
arr3d

array([[[12, 13, 14, 15],
        [21, 32, 43, 54],
        [ 1,  5,  3,  2]]])

In [17]:
arr3d.shape #shape[no.of 2d, r,col]

(1, 3, 4)

In [19]:
arr3d.ndim

3

In [20]:
arr3d[0][2]  

array([1, 5, 3, 2])

In [33]:
arr3d2= np.arange(32).reshape(2,4,4)
arr3d2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [34]:
arr3d2[0,:2,1]

array([1, 5])

In [0]:
arr = np.arange(1,37).reshape(6,6)

In [41]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [42]:
arr[2:4,2:5]

array([[15, 16, 17],
       [21, 22, 23]])

In [43]:
arr3d2[1,1:3,1:3]

array([[21, 22],
       [25, 26]])

In [45]:
arr[2:3,:6] #2:3 will print 1 row & prints 2d row

array([[13, 14, 15, 16, 17, 18]])

In [47]:
arr[4:5,:]

array([[25, 26, 27, 28, 29, 30]])

In [48]:
arr[4:5,]

array([[25, 26, 27, 28, 29, 30]])

In [49]:
arr[4:5]

array([[25, 26, 27, 28, 29, 30]])

In [50]:
arr[2]

array([13, 14, 15, 16, 17, 18])

In [51]:
arr[:,3] #row can be left blank but if you want to print col row is mandatory

array([ 4, 10, 16, 22, 28, 34])

In [52]:
arr[1:5,:]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [53]:
arr[1:5,0:6]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [54]:
arr[2:4,5:6]  #write : in col to get vector

array([[18],
       [24]])

In [55]:
arr[2:4,5]

array([18, 24])

In [56]:
arr[2:4,-1]

array([18, 24])

In [57]:
#to print alternate col
arr[:,::2]  #:2 step gives alternate results

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [58]:
arr[::2,:]  #:2 step gives alternate results for rows

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [59]:
arr[0:5:2,::2]  #slicing in rows and col
'''0: 5 range in row :2 skip a row
::2 takes alternate col

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [60]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [97]:
#Bolean indexing
names= np.array(['bob','jeo','will','bob','will','jeo','jeo'])
names #python save data in U4

array(['bob', 'jeo', 'will', 'bob', 'will', 'jeo', 'jeo'], dtype='<U4')

In [0]:
data = np.random.randn(7,4)

In [63]:
data>1

array([[False, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [99]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [66]:
#for printing exact values use variable frame you want to map it on in this case data frame
'''fetches values more than 1'''
data[data>1]

array([1.53819183, 2.54463456, 1.84455614, 1.19045367])

In [68]:
print(names=='bob') 

[ True False False  True False False False]


In [69]:
data[names == 'bob']  #this will map on data thats why it will only fetch 2 rows

array([[-0.92449351,  0.75012969, -1.38066843,  1.53819183],
       [-0.25873311,  1.84455614, -0.19800455,  0.00862961]])

In [70]:
bol = np.array([True,False,False,False,False,True,False],dtype= 'bool')
data[bol]
# bol is mapping on data

array([[-0.92449351,  0.75012969, -1.38066843,  1.53819183],
       [ 0.77736223,  0.36298847, -0.42720187,  0.40996577]])

In [100]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [101]:
condition = names != 'bob'
condition


array([False,  True,  True, False,  True,  True,  True])

In [85]:
data[condition]

array([], shape=(0, 7, 4), dtype=float64)

In [96]:
names != 'bob'
names

'bob'

In [87]:
#~ uses for reverse
data[~condition]

array([ 1.19045367, -0.20105078, -0.29423461, -0.26368049])

In [91]:
data

array([[-0.92449351,  0.75012969, -1.38066843,  1.53819183],
       [ 0.82140167,  0.22623303, -1.9497319 , -1.75133251],
       [-1.56178946,  2.54463456, -1.33591135, -0.81827817],
       [-0.25873311,  1.84455614, -0.19800455,  0.00862961],
       [-0.73703641,  0.0081056 ,  0.20825622, -0.61464813],
       [ 0.77736223,  0.36298847, -0.42720187,  0.40996577],
       [ 1.19045367, -0.20105078, -0.29423461, -0.26368049]])

In [93]:
data[~ condition,3]

-0.2636804884765017

In [95]:
data[~condition, 1:3]

array([-0.20105078, -0.29423461])

In [104]:
#condition = names != bob
data = np.arange(28).reshape(7,4)
print(data)
print(condition)
data[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [105]:
print(data)
print(condition)
data[~condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2],
       [13, 14]])

In [106]:
#multiple condition
names

array(['bob', 'jeo', 'will', 'bob', 'will', 'jeo', 'jeo'], dtype='<U4')

In [0]:
#and or does not work on numpy
cond = (names=="bob") & (names == "jeo")

In [109]:
cond

array([False, False, False, False, False, False, False])

In [111]:
cond1 = (names=="bob") | (names == "jeo")
cond1

array([ True,  True, False,  True, False,  True,  True])

In [114]:
#Fancy indexing
arre = np.empty((8,4))
arre

array([[1.92911054e-316, 1.02271589e-321, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.00833776e+151, 9.95923263e-143,
        9.49677371e+170],
       [3.51147619e+151, 1.30593186e+214, 1.06400250e+248,
        8.03408341e-095],
       [2.65292601e+180, 6.92419521e+218, 4.47303447e-143,
        2.20198284e-094],
       [8.37170554e-144, 3.59531471e+246, 8.73765703e+183,
        1.65341891e+137],
       [8.73970966e+183, 4.11596382e+223, 7.30654544e+141,
        1.79189080e+132],
       [8.78575565e+252, 1.67494822e+243, 1.69374332e+190,
        1.96099265e+243],
       [4.50618371e-144, 1.95288227e+233, 2.60097910e-306,
        0.00000000e+000]])

In [0]:
arred = np.empty((8,4))
for t in range(8):
  arred[t] = t

In [117]:
arred

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [118]:
arred[[1,2,3]]  # arred sees this as a list


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [120]:
arred[[4,0,1,7]]  #[[]] is important to print 2d

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [124]:
arred[[4,0,1,7],[2,1,2,0]] # making an ordered pair (4,2),(0,1),(1,2),(7,0)

array([4., 0., 1., 7.])

In [127]:
print(arred)

arred[[1,5,7,2]][:,[0,3,1,2]]

#explaination  1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
#positions(1,0)(1,3)(1,1)(1,2).... and so on

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [128]:
#transpose
arred.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [129]:
arred.transpose()

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [0]:
arred.sort()

In [131]:
arred

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [0]:
s =[3423,43534,22,33,22,44,554,0,9,0]


In [133]:
s

[3423, 43534, 22, 33, 22, 44, 554, 0, 9, 0]

In [134]:
a=set(s)
a  # unique and set will remove repeated values
''' our variables dissapear when system shuts down 
extension changes when zip npz

{0, 9, 22, 33, 44, 554, 3423, 43534}

In [0]:
#contactenate
arr1 = np.arange(9).reshape(3,3)

In [138]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
arr2 = np.array([[1,2,3],[4,44,32],[98,12,133]])
arr2
#matrix increase3 vertically means rows will increase in real it will increase horizontally

array([[  1,   2,   3],
       [  4,  44,  32],
       [ 98,  12, 133]])

In [144]:
'''np.concatenate([arr1,arr2],axis =1) for col
np.concatenate([arr1,arr2],axis =0) for row'''
np.concatenate([arr1,arr2],axis =1)  #increases col


array([[  0,   1,   2,   1,   2,   3],
       [  3,   4,   5,   4,  44,  32],
       [  6,   7,   8,  98,  12, 133]])

In [147]:
np.concatenate([arr1,arr2],axis =0) #increases rows

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  1,   2,   3],
       [  4,  44,  32],
       [ 98,  12, 133]])

In [149]:
#vstack and hstack
np.stack([arr1,arr2]) #remember []

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]],

       [[  1,   2,   3],
        [  4,  44,  32],
        [ 98,  12, 133]]])

In [150]:
np.vstack([arr1,arr2]) #vertical stack rows will increase

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  1,   2,   3],
       [  4,  44,  32],
       [ 98,  12, 133]])

In [151]:
np.hstack([arr1,arr2]) #horizontal stack cols will increase

array([[  0,   1,   2,   1,   2,   3],
       [  3,   4,   5,   4,  44,  32],
       [  6,   7,   8,  98,  12, 133]])

In [0]:
aw= np.arange(36).reshape(6,6)

In [155]:
aw

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [156]:
'''2 types of split 
np.vsplit()
np.hsplit()'''
np.vsplit(aw,3)# cuts horizontally

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [163]:
np.hsplit(aw,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [164]:
np.tile(aw,2) #can also give axis

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 30, 31, 32, 33, 34, 35]])